# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(493, 176)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mode_horizontal_layout = QtWidgets.QHBoxLayout()
        self.mode_horizontal_layout.setObjectName("mode_horizontal_layout")
        self.mode_label = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mode_label.setFont(font)
        self.mode_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.mode_label.setObjectName("mode_label")
        self.mode_horizontal_layout.addWidget(self.mode_label)
        self.mode_combo_box = QtWidgets.QComboBox(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mode_combo_box.setFont(font)
        self.mode_combo_box.setObjectName("mode_combo_box")
        self.mode_combo_box.addItem("")
        self.mode_combo_box.addItem("")
        self.mode_combo_box.addItem("")
        self.mode_horizontal_layout.addWidget(self.mode_combo_box)
        self.verticalLayout.addLayout(self.mode_horizontal_layout)
        self.path_group_box = QtWidgets.QGroupBox(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_group_box.setFont(font)
        self.path_group_box.setObjectName("path_group_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.path_group_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.path_line_edit = QtWidgets.QLineEdit(self.path_group_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.path_line_edit.setFont(font)
        self.path_line_edit.setObjectName("path_line_edit")
        self.horizontalLayout_4.addWidget(self.path_line_edit)
        self.browse_push_button = QtWidgets.QPushButton(self.path_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_push_button.sizePolicy().hasHeightForWidth())
        self.browse_push_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.browse_push_button.setFont(font)
        self.browse_push_button.setObjectName("browse_push_button")
        self.horizontalLayout_4.addWidget(self.browse_push_button)
        self.verticalLayout.addWidget(self.path_group_box)
        self.start_horizontal_layout = QtWidgets.QHBoxLayout()
        self.start_horizontal_layout.setObjectName("start_horizontal_layout")
        self.start_push_button = QtWidgets.QPushButton(self.central_widget)
        self.start_push_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_push_button.sizePolicy().hasHeightForWidth())
        self.start_push_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_push_button.setFont(font)
        self.start_push_button.setObjectName("start_push_button")
        self.start_horizontal_layout.addWidget(self.start_push_button)
        self.verticalLayout.addLayout(self.start_horizontal_layout)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 20))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        
        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)
    
    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.mode_label.setText(_translate("main_window", "TextLabel"))
        self.mode_combo_box.setItemText(0, _translate("main_window", "Album"))
        self.mode_combo_box.setItemText(1, _translate("main_window", "Band"))
        self.mode_combo_box.setItemText(2, _translate("main_window", "Compilation"))
        self.path_group_box.setTitle(_translate("main_window", "Path"))
        self.browse_push_button.setText(_translate("main_window", "Browse"))
        self.start_push_button.setText(_translate("main_window", "Start"))
